import type { NextPage } from "next";
import { Divider, Stack } from "@mui/material";
import { AuthBanner } from "@/components/auth/AuthBanner";
import { ActiveGameBanner } from "@/components/game/ActiveGameBanner";
import { useAtomValue } from "jotai";
import { userAtom } from "@/atoms";
import Image from "next/image";
import { FlexCenter } from "@/components/flex/FlexCenter";
import { Fragment } from "react";
import { makeStyles } from "tss-react/mui";

const useStyles = makeStyles()({
  HeroImage: {
    objectFit: "contain",
    textAlign: "center",
  },
});

const Hero = () => {
  const { classes } = useStyles();

  return (
    <FlexCenter>
      <Image
        src={"/hero-picture.png"}
        alt={
          "a bunch of random character drawings generated by dall-e artificial intelligence"
        }
        className={classes.HeroImage}
        width={300}
        height={300}
      />
    </FlexCenter>
  );
};

const Home: NextPage = () => {
  const user = useAtomValue(userAtom);
  const signedIn = Boolean(user);

  return (
    <Stack spacing={4}>
      {!signedIn && <Hero />}

      <AuthBanner />

      {signedIn && (
        <Fragment>
          <Divider />
          <ActiveGameBanner />
        </Fragment>
      )}
    </Stack>
  );
};

export default Home;
