import { userAtom } from "@/atoms";
import { AuthBanner } from "@/components/auth/AuthBanner";
import { FlexCenter } from "@/components/flex/FlexCenter";
import { ActiveGameBanner } from "@/components/game/ActiveGameBanner";
import { Container, Divider, Stack } from "@mui/material";
import { useAtomValue } from "jotai";
import type { NextPage } from "next";
import Image from "next/image";
import { Fragment } from "react";
import { makeStyles } from "tss-react/mui";

const useStyles = makeStyles()({
  HeroImage: {
    objectFit: "contain",
    textAlign: "center",
  },
});

const Hero = () => {
  const { classes } = useStyles();

  return (
    <FlexCenter>
      <Image
        src={"/hero-picture.png"}
        alt={
          "a bunch of random character drawings generated by dall-e artificial intelligence"
        }
        className={classes.HeroImage}
        width={300}
        height={300}
      />
    </FlexCenter>
  );
};

const Home: NextPage = () => {
  const user = useAtomValue(userAtom);
  const signedIn = Boolean(user);

  return (
    <Container maxWidth={"lg"}>
      <Stack spacing={4}>
        {!signedIn && <Hero />}

        <AuthBanner />

        {signedIn && (
          <Fragment>
            <Divider />
            <ActiveGameBanner />
          </Fragment>
        )}
      </Stack>
    </Container>
  );
};

export default Home;
